### PR TITLE
Fix various warnings

### PR DESCRIPTION
**Pull request by dutkalex**
**_Describe your changes here:_**
Title says it all

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [x] The author added a BSD statement to `doc/` (or already has one)

### CODE REVIEW

**Review by sandro-elsweijer — APPROVED** [review]

**Comment by sandro-elsweijer** [comment]
@dutkalex Please indent the code and then we can merge it. Thank you for you contribution!

**Comment by dutkalex** [comment]
Hi @sandro-elsweijer
Unfortunately the indent script does not work on my machine (same problem as for #1118 #1223 ) 😕

**Comment by sandro-elsweijer** [comment]
@dutkalex 
We relaxed the requirements for the indent script, maybe it works now.
If you use conda, a `conda install clang-format=17.0` should do the trick :)

If you do not use conda, `pip install clang-format=17.0` should also work, but I did not test this

If it still does not work I can again branch off from your branch and indent myself

**Comment by dutkalex** [comment]
Hmm... Maybe I'm doing it wrong then 🧐
Just to be sure: what is your command line for indenting the PR? @sandro-elsweijer

**Comment by sandro-elsweijer** [comment]
> Hmm... Maybe I'm doing it wrong then 🧐 Just to be sure: what is your command line for indenting the PR? @sandro-elsweijer

```bash
./scripts/t8indent path/to/file/to/indent
```
or
```bash
(cd scripts; ./indent_all_files.scp)
```

**Comment by dutkalex** [comment]
Ok so got to the bottom of this. Turns out it was a GNU-find vs. BSD-find problem. 
The trick that made it work: `brew install findutils` + replacing `find` by `gfind` in `scripts/find_all_source_files.scp`

**Comment by dutkalex** [comment]
> @dutkalex Please indent the code and then we can merge it. Thank you for you contribution!

@sandro-elsweijer Done

**Comment by sandro-elsweijer** [comment]
Nice, during the release of 3.0 the main branch was locked, but I will merge this as soon as it gets unlocked

**Pull request merged**
