### PR TITLE
Fix issue 142 - t8_face_leaf_neighbors

### LINKED ISSUE #142: Split up t8_forest_leaf_face_neighbors
t8_forest_leaf_face_neighbors provides a lot of functionality.
Sometimes not all of this is required but the caller still needs to provide allocated memory. There should be subfunctions for

- only get the number of face neighbors
- set output vars to NULL lets the function ignore them

### PR DESCRIPTION
**Pull request by jfussbro**
**_Describe your changes here:_**

Before, t8_forest_leaf_face_neighbors dynamically allocated and freed memory for the leaf_face_neighbors for every face. Now, the caller of the function is responsible for the allocation of the memory and passes pointers to the allocated arrays into the function.
If the caller passes null-pointers it is considert, that information about leaf_face_neighbors is not needed and they will not be calculated.

Closes #142 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

### CODE REVIEW

**Comment by Davknapp** [comment]
All tests are failing, please have another look at it ;)

**Comment by jmark** [comment]
@jfussbro Would be please revive this PR?

Please merge the latest `main`.

Furthermore, please create a wrapper function which emulates the old signature. That is the wrapper allocates the arrays and passes them to your modified function. We want to keep backwards compatibility for now.

I suggest to call the wrapper function like the old version and the modified (without array allocations) gets another name. E.g.,
`t8_forest_leaf_face_neighbors_ext`.

We will add the query for the `orientation` in the `*_ext` version, too. But one step at the time.

**Comment by holke** [comment]
Thanks for this change.

Some remarks:

If the caller is responsible for allocating the memory, we should provide a function that does so.
i.e. `t8_leaf_face_neighbor_alloc/free` or similar.
Also the documentation must be very clear here since letting the user manage the memory can lead to trip falls.
I.e user allocates memory for an element with 4 face neighbors and uses the same memory for the next element but it has 6 neighbors but user does not remember to allocate new memory.

The user must be aware that this can happen and what they can do to prevent.

Additionally, #142 suggest splitting up the function into subfunction. One of them calculating the number of neighbors.

**Comment by jmark** [comment]
> Thanks for this change.
> 
> Some remarks:
> 
> If the caller is responsible for allocating the memory, we should provide a function that does so. i.e. `t8_leaf_face_neighbor_alloc/free` or similar. Also the documentation must be very clear here since letting the user manage the memory can lead to trip falls. I.e user allocates memory for an element with 4 face neighbors and uses the same memory for the next element but it has 6 neighbors but user does not remember to allocate new memory.
> 
> The user must be aware that this can happen and what they can do to prevent.
> 
> Additionally, #142 suggest splitting up the function into subfunction. One of them calculating the number of neighbors.

Thanks for the thoughts. I actually thought that a user calling this routine can even use static arrays being part of the function stack. The arrays just have to be large enough. I suggest to simply use constants ala `T8_MAX_NUM_FACE_CHILDREN` or similar.

That way the user has full control and exactly knows where and when memory is allocated.

**Comment by jmark** [comment]
@jfussbro As we discussed I close this PR.

**Pull request closed without merging**
