### PR TITLE
Use new docker image for t8code tests

### LINKED ISSUE #24: Improve the CI by using a precompiled container.
We currently need to download and install mpich each time when we start our CI script.
This can be improved by using a container (docker) that we preconfigure.

### LINKED ISSUE #140: Add vtk linkage to CI
At least one of our CI runs should link to VTK and test the VTK API output.

### LINKED ISSUE #276: CI does not check make install for t8code
Our CI checks `make install` for sc and p4est, but not for t8code itself.

### LINKED ISSUE #611: Serial CI job doesn't complain about MPI macros
There is a CI job without MPI enabled, but even though there was usage of `MPI_INT` instead of `sc_MPI_INT` in the code, the job compiled without error.
The problem only occured on a workstation with manual compilation, but should also be detected by the CI.

See: https://github.com/DLR-AMR/t8code/pull/610

### PR DESCRIPTION
**Pull request by sandro-elsweijer**
**_Describe your changes here:_**
1. Uses a docker container to run the tests. This was, we can install all dependencies beforehand in the docker image (e.g. the VTK installation, which needs up to an hour) (Closes #24)
2. Adds a VTK testing configuration (Closes #140)
3. Changes the OCC and NetCDF tests to the debug configuration, to also catch assertions in the code
4. Adds checks for the `make install -j` command (Closes #276)
5. Split up test files for parallel testing. Reduces CI time from 30 min to 22 min
6. Catches errors which werent catched before (Closes #611 )

**#4inarow**

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [x] The reviewer executed the new code features at least once and checked the results manually

- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] New source/header files are properly added to the Makefiles
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [x] The code is covered in an existing or new test case using Google Test

#### Github action

- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [x] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [x] Should this use case be added to the github action?
  - [x] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [x] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [x] New Datatypes are added to t8indent_custom_datatypes.txt
- [x] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [x] The author added a BSD statement to `doc/` (or already has one)

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
The upload of logs was tested here: https://github.com/DLR-AMR/t8code/actions/runs/4973151350

**Comment by sandro-elsweijer** [comment]
The new tests are quite slow because of the docker environment. Maybe somebody has some tips about speeding this up.

**Comment by Davknapp** [comment]
All runs use "-O3", there should be at least one run with "-O0" in my opinion.

**Review by Davknapp — COMMENTED** [review]
Looks good in general, please address my comment and have a look at my adaptations.

**Review by jmark — APPROVED** [review]

**Pull request merged**
