### PR TITLE
Feature camera projection

### PR DESCRIPTION
**Pull request by Davknapp**
Implemented basic transformation matrices with the goal to visualize meshes as tikz-pictures in latex-documents. 

We want to transform the points of the elements of the mesh via a very basic rendering-pipeline. The user will be able to define the output-screen, a camera and a view volume. The coordinates of the mesh will then be transformed into the coordinate-system of the camera. Using a perspective projection into a unit-cube we will be able to skip points outside of the view-volume during visualization (clipping). From the unit-cube we project the points onto the output-screen. 

The camera is defined as single point. The view-direction of the camera is given via a single point. The view-volume is a frustom starting at this point. The side orthogonal to the view-direction is defined by giving its width and height. All other sides are implicitly defined by giving the distance from the camera to back-side of the frustom. 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] New tests use the Google Test framework
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

### CODE REVIEW

**Comment by holke** [comment]
Maybe this is  better as an own project, similar to png2mesh.
mesh2tikz or t8code2tikz

**Comment by cburstedde** [comment]
> Maybe this is  better as an own project, similar to png2mesh.
> mesh2tikz or t8code2tikz

Can a very primitive version be placed in libsc?  We'll be needing a camera
abstraction as well for p4est.

**Comment by Davknapp** [comment]
> Maybe this is better as an own project, similar to png2mesh. mesh2tikz or t8code2tikz

An implementation can be found here: https://github.com/Davknapp/mesh2tikz

**Comment by Davknapp** [comment]
> Maybe this is better as an own project, similar to png2mesh. mesh2tikz or t8code2tikz
> Can a very primitive version be placed in libsc? We'll be needing a camera abstraction as well for p4est.

Yes, I can add a camera abstraction to libsc!

**Comment by sandro-elsweijer** [comment]
Moved to https://github.com/DLR-AMR/mesh2tikz repository

**Pull request closed without merging**
