### PR TITLE
Simplified C interface for registering geometries in cmeshes.

### PR DESCRIPTION
**Pull request by jmark**
**_Describe your changes here:_**

I basically just switched from a pointer-pointer to just a pointer. I see no reason why an application should manage a reference to the pointer of a geometry. Besides, I'm having troubles with the garbage collector in Julia wiping the reference to the geometry away.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
It was implemented this way, because the geometry handler takes ownership of the geometry and puts it inside a unique ptr. Depending on the unique pointer, the location of the geometry could change and this way the reference provided by the user would point into nothingness. This is unexpected behavior and really hard to debug.
This could lead to troubles if the user wants to use some functionality of the geometry after assigning it to the cmesh. This for example happens with curved geometries, when the geometry is asked for topology information.

**Comment by jmark** [comment]
> It was implemented this way, because the geometry handler takes ownership of the geometry and puts it inside a unique ptr. Depending on the unique pointer, the location of the geometry could change and this way the reference provided by the user would point into nothingness. This is unexpected behavior and really hard to debug. This could lead to troubles if the user wants to use some functionality of the geometry after assigning it to the cmesh. This for example happens with curved geometries, when the geometry is asked for topology information.

@sandro-elsweijer Thank you for your explanation! Appreciated!

The reasoning why you did it this way in general is already clear to me. However, in my opinion, your approach s not well thought through by breaking well established software design patterns.

The already existing documentation is crystal clear about the expected behavior:
```
/** Register a geometry in the cmesh. The cmesh takes ownership of the geometry.
```
The user cannot expect to properly use the geometry anymore, once it has given up ownership to t8code.

If you really want to provide use cases where the user and t8code share the geometry then we have to think about different approaches. For example, having a two copies of the geometry. If the geometry is expensive than the copies of the geometry should share the expensive routines/data.

**Comment by sandro-elsweijer** [comment]
> > It was implemented this way, because the geometry handler takes ownership of the geometry and puts it inside a unique ptr. Depending on the unique pointer, the location of the geometry could change and this way the reference provided by the user would point into nothingness. This is unexpected behavior and really hard to debug. This could lead to troubles if the user wants to use some functionality of the geometry after assigning it to the cmesh. This for example happens with curved geometries, when the geometry is asked for topology information.
> 
> @sandro-elsweijer Thank you for your explanation! Appreciated!
> 
> The reasoning why you did it this way in general is already clear to me. However, in my opinion, your approach is not well thought through by breaking well established software design patterns.
> 
> The already existing documentation is crystal clear about the expected behavior:
> 
> ```
> /** Register a geometry in the cmesh. The cmesh takes ownership of the geometry.
> ```
> 
> The user cannot expect to properly use the geometry anymore, once it has given up ownership to t8code.
> 
> If you really want to provide use cases where the user and t8code share the geometry then we have to think about different approaches. For example, having two copies of the geometry. If the geometry is expensive than the copies of the geometry should share the expensive routines/data.

The two copy option is especially with OCCs memory management really hard.
But since this is just the C interface and the geometry classes members cannot be accessed in C anyway, we can do it this way. Users who want to use the geometry afterwards can just use the CPP interface.
But please adapt the [register_geometry](https://github.com/DLR-AMR/t8code/blob/b64c7eb021f1cda7d5753b70d516a1798c010f6e/src/t8_geometry/t8_geometry_handler.cxx#L38-L43) member function of the handler as well.

**Review by sandro-elsweijer — CHANGES_REQUESTED** [review]
> > It was implemented this way, because the geometry handler takes ownership of the geometry and puts it inside a unique ptr. Depending on the unique pointer, the location of the geometry could change and this way the reference provided by the user would point into nothingness. This is unexpected behavior and really hard to debug. This could lead to troubles if the user wants to use some functionality of the geometry after assigning it to the cmesh. This for example happens with curved geometries, when the geometry is asked for topology information.
> 
> @sandro-elsweijer Thank you for your explanation! Appreciated!
> 
> The reasoning why you did it this way in general is already clear to me. However, in my opinion, your approach is not well thought through by breaking well established software design patterns.
> 
> The already existing documentation is crystal clear about the expected behavior:
> 
> ```
> /** Register a geometry in the cmesh. The cmesh takes ownership of the geometry.
> ```
> 
> The user cannot expect to properly use the geometry anymore, once it has given up ownership to t8code.
> 
> If you really want to provide use cases where the user and t8code share the geometry then we have to think about different approaches. For example, having two copies of the geometry. If the geometry is expensive than the copies of the geometry should share the expensive routines/data.

The two copy option is especially with OCCs memory management really hard.
But since this is just the C interface and the geometry classes members cannot be accessed in C anyway, we can do it this way. Users who want to use the geometry afterwards can just use the CPP interface.
But please adapt the [register_geometry](https://github.com/DLR-AMR/t8code/blob/b64c7eb021f1cda7d5753b70d516a1798c010f6e/src/t8_geometry/t8_geometry_handler.cxx#L38-L43) member function of the handler as well.

**Comment by jmark** [comment]
> The two copy option is especially with OCCs memory management really hard. But since this is just the C interface and the geometry classes members cannot be accessed in C anyway, we can do it this way. Users who want to use the geometry afterwards can just use the CPP interface. But please adapt the [register_geometry](https://github.com/DLR-AMR/t8code/blob/b64c7eb021f1cda7d5753b70d516a1798c010f6e/src/t8_geometry/t8_geometry_handler.cxx#L38-L43) member function of the handler as well.

Fair enough! Adapted the `register_geometry` member function as you said.

**Review by sandro-elsweijer — APPROVED** [review]
lgtm!

**Pull request merged**
