### PR TITLE
Feature transition | removing hanging faces from adaptive 2D quadrilateral meshes

### PR DESCRIPTION
**Pull request by Flo1314**
**_Describe your changes here:_**

This is the PR to enable transition cells (a family of triangular subelements) for the 2D quad scheme. Transition cells can be used to make the adaptive mesh conformal by inserting additional triangular subelements into a balanced mesh.

The transition subroutine is similar to balance. It iterates through the mesh and refines elements whenever these have a specific property (having hanging faces in our case).

To enable the transition feature, use the set_transition function just as set_balance for example. To use the transition subroutine, the mesh must be balanced. If set_balance ist not set, but set_transition is, then set_balance will be set automatically.

The key extensions of this feature are:

1) a new refinement scheme in `src/t8_schemes/t8_quad_transition` that has all the element functions for quad elements and additional or extended functions for triangular subelements and transition cells.

2) a new refinement callback function, defined in `src/t8_forest/t8_forest_transition` that translates hanging faces of a current element into a refinement value >1, corresponding to a so called transition type. 

3) adjustments to the `t8_forest_adapt.cxx` file such that it can process these new refinement values >1.

4) the LFN function has been extended, such that neighbor elements in transitioned meshes can be identified by using the Morton Index and the Subelement ID. 

5) the ghost V1 algorithm has been extended. Transitioned meshes can now be used in parallel. In contrast to a standard quad mesh, the elements will not be equally (+-1) partitioned onto all processes since we call partition after balance and before transition in order to ensure that whole families of transition cells will be in one and the same process.

6) three examples in the new `examples/transition` directory. `t8_refinement_transition` can be used to construct adaptive meshes with multiple timesteps. The meshes can be transitioned and monitoring settings as well as a LFN test are available. `t8_advection_transition` solves the advection equation with transitioned meshes. `t8_testing_subelement_functions` constructs a single element which can be used to call `t8_element` functions for debugging and other low level tests.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Comment by Flo1314** [comment]
Running the following command

  `$ ./scripts/t8indent example/transition/t8_refinement_transition.cxx`

results in

  `./scripts/t8indent: line 96: -bap: command not found`

Tested on Philipps workstation and my local Ubuntu VM in my own feature-branch and the current DLR-AMR/t8code main.

**Comment by Flo1314** [comment]
Add subelement/transition tests

**Comment by Flo1314** [comment]
TODO: all tests pass, except for `t8_gtest_main` - why?

**Comment by holke** [comment]
> TODO: indent code.
> 
> Running the following command
> 
> `$ ./scripts/t8indent example/transition/t8_refinement_transition.cxx`
> 
> results in
> 
> `./scripts/t8indent: line 96: -bap: command not found`
> 
> Tested on Philipps workstation and my local Ubuntu VM in my own feature-branch and the current DLR-AMR/t8code main.

This is probably due to an older version of `indent` on the workstation...
I have version `2.2.11`, whats your version?

**Comment by Flo1314** [comment]
> 

```bash
beck_f2@sc-030121l:~$ indent --version

Command 'indent' not found, but can be installed with:

apt install indent
Please ask your administrator.
```

I dont want to comment on this :D but thanks

**Comment by holke** [comment]
When running the program `./t8_advection_transition` i get the following error

```bash
[t8] Done t8_forest_transition.
[t8 0] Committed forest with 2072 local elements and 2072 global elements.
	Tree range ist from 0 to 0.
[t8 0] balance_time: 0.855152
[t8 0] transition_time: 0.793214
[t8 0] Building offsets for forest 0x55b9e77dafa0
[t8 0] Building global first descendants for forest 0x55b9e77dafa0
[t8] Into t8_forest_iterate_replace
[libsc 0] Abort: Assertion 'vertex >= 0 && vertex < T8_SUBELEMENT_FACES'
[libsc 0] Abort: ../../source/t8code-second-worktree/src/t8_schemes/t8_quads_transition/t8_transition/t8_transition_quad_cxx.cxx:1464
[libsc 0] Abort: Obtained 16 stack frames
[libsc 0] Stack 0: libsc-2.8.1.5-0b70-dirty.so(+0xc70f) [0x7f6075e0670f]
[libsc 0] Stack 1: libsc-2.8.1.5-0b70-dirty.so(sc_abort+0xd) [0x7f6075e066ce]
[libsc 0] Stack 2: libsc-2.8.1.5-0b70-dirty.so(sc_abort_verbosef+0) [0x7f6075e0696f]
[libsc 0] Stack 3: libt8-1.0.0.591-f908f.so(_ZN27t8_subelement_scheme_quad_c38t8_element_vertex_coords_of_subelementEPK10t8_elementiPi+0xd2) [0x7f60760d850a]
[libsc 0] Stack 4: libt8-1.0.0.591-f908f.so(_ZN27t8_subelement_scheme_quad_c24t8_element_vertex_coordsEPK10t8_elementiPi+0x126) [0x7f60760d8434]
[libsc 0] Stack 5: libt8-1.0.0.591-f908f.so(_ZN27t8_subelement_scheme_quad_c34t8_element_vertex_reference_coordsEPK10t8_elementiPd+0x4f) [0x7f60760d82bd]
[libsc 0] Stack 6: libt8-1.0.0.591-f908f.so(t8_forest_element_coordinate+0xb7) [0x7f60760a4180]
[libsc 0] Stack 7: libt8-1.0.0.591-f908f.so(t8_forest_element_centroid+0x116) [0x7f60760a4431]
[libsc 0] Stack 8: t8_advection_transition(+0x4195) [0x55b9e5915195]
[libsc 0] Stack 9: t8_advection_transition(+0x70dd) [0x55b9e59180dd]
[libsc 0] Stack 10: libt8-1.0.0.591-f908f.so(t8_forest_iterate_replace+0x751) [0x7f60760b409c]
[libsc 0] Stack 11: t8_advection_transition(+0x7f7f) [0x55b9e5918f7f]
[libsc 0] Stack 12: t8_advection_transition(+0x9aa2) [0x55b9e591aaa2]
[libsc 0] Stack 13: t8_advection_transition(+0xbc94) [0x55b9e591cc94]
[libsc 0] Stack 14: libc.so.6(__libc_start_main+0xe7) [0x7f607512cc87]
[libsc 0] Stack 15: t8_advection_transition(+0x2daa) [0x55b9e5913daa]
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

**Comment by holke** [comment]
Unfortunately, this code throws errors in png2mesh, am i doing something wrong?
```C++
  for (ilevel = level; ilevel < adapt_context->maxlevel; ++ilevel) {
    t8_forest_set_user_data (forest, (void *) adapt_context);
    printf ("Starting search on level %i\n", ilevel);
    /* Fill adapt markers array */
    const t8_locidx_t   num_elements =
      t8_forest_get_local_num_elements (forest);
    t8_locidx_t         ielement;
    sc_array_resize ((sc_array_t *) &adapt_context->refinement_markers,
                     num_elements);
    for (ielement = 0; ielement < num_elements; ++ielement) {
      /* Set all refinement markers to 0. */
      *(int *) t8_sc_array_index_locidx ((sc_array_t *)
                                         &adapt_context->refinement_markers,
                                         ielement) = 0;
    }
    /* Search and create the refinement markers. */
    t8_forest_search (forest, png2mesh_search_callback,
                      png2mesh_search_callback, &search_queries);
    t8_forest_init (&forest_adapt);
    t8_forest_set_adapt (forest_adapt, forest, png2mesh_adapt, 0);
    t8_forest_set_partition (forest_adapt, forest, 0);
    if (element_choice == 3) {
	  t8_forest_set_balance (forest_adapt, forest, 0);
      t8_forest_set_transition (forest_adapt, forest);
    }
    t8_forest_commit (forest_adapt);
    forest = forest_adapt;
  }
```
The error is
```bash
Starting program: /home/holke/source/png2mesh/build/png2mesh_demo -f weihnachtsbaum.png -m 3 -e3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[libsc] This is libsc 2.8.1.5-0b70-dirty
[t8] This is t8 1.0.0.591-f908f
[t8] CPP                      mpicc -E
[t8] CPPFLAGS                 
[t8] CC                       mpicc
[t8] CFLAGS                   -O0 -g
[t8] LDFLAGS                  
[t8] LIBS                     -lz -lm  -lstdc++

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b6dafd in t8_forest_compute_maxlevel (forest=0x5555561a25a0)
    at ../../source/t8code-second-worktree/src/t8_forest/t8_forest_cxx.cxx:62
62	      maxlevel = ts->t8_element_maxlevel ();
(gdb) where
#0  0x00007ffff7b6dafd in t8_forest_compute_maxlevel (forest=0x5555561a25a0)
    at ../../source/t8code-second-worktree/src/t8_forest/t8_forest_cxx.cxx:62
#1  0x00007ffff7b63f87 in t8_forest_commit (forest=0x5555561a25a0)
    at ../../source/t8code-second-worktree/src/t8_forest/t8_forest.c:545
#2  0x00007ffff7b6678b in t8_forest_new_uniform (cmesh=0x5555557a3000, scheme=0x5555557a5f40, level=0, 
    do_face_ghost=0, comm=1140850688) at ../../source/t8code-second-worktree/src/t8_forest/t8_forest.c:1669
#3  0x0000555555556cdd in build_forest(int, int, int, png2mesh_adapt_context_t const*) ()
#4  0x00005555555573ea in main ()
(gdb) 
```

**Comment by holke** [comment]
> Unfortunately, this code throws errors in png2mesh, am i doing something wrong?
> 
> ```c++
>   for (ilevel = level; ilevel < adapt_context->maxlevel; ++ilevel) {
>     t8_forest_set_user_data (forest, (void *) adapt_context);
>     printf ("Starting search on level %i\n", ilevel);
>     /* Fill adapt markers array */
>     const t8_locidx_t   num_elements =
>       t8_forest_get_local_num_elements (forest);
>     t8_locidx_t         ielement;
>     sc_array_resize ((sc_array_t *) &adapt_context->refinement_markers,
>                      num_elements);
>     for (ielement = 0; ielement < num_elements; ++ielement) {
>       /* Set all refinement markers to 0. */
>       *(int *) t8_sc_array_index_locidx ((sc_array_t *)
>                                          &adapt_context->refinement_markers,
>                                          ielement) = 0;
>     }
>     /* Search and create the refinement markers. */
>     t8_forest_search (forest, png2mesh_search_callback,
>                       png2mesh_search_callback, &search_queries);
>     t8_forest_init (&forest_adapt);
>     t8_forest_set_adapt (forest_adapt, forest, png2mesh_adapt, 0);
>     t8_forest_set_partition (forest_adapt, forest, 0);
>     if (element_choice == 3) {
> 	  t8_forest_set_balance (forest_adapt, forest, 0);
>       t8_forest_set_transition (forest_adapt, forest);
>     }
>     t8_forest_commit (forest_adapt);
>     forest = forest_adapt;
>   }
> ```
> 
> The error is
> 
> ```shell
> Starting program: /home/holke/source/png2mesh/build/png2mesh_demo -f weihnachtsbaum.png -m 3 -e3
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [libsc] This is libsc 2.8.1.5-0b70-dirty
> [t8] This is t8 1.0.0.591-f908f
> [t8] CPP                      mpicc -E
> [t8] CPPFLAGS                 
> [t8] CC                       mpicc
> [t8] CFLAGS                   -O0 -g
> [t8] LDFLAGS                  
> [t8] LIBS                     -lz -lm  -lstdc++
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff7b6dafd in t8_forest_compute_maxlevel (forest=0x5555561a25a0)
>     at ../../source/t8code-second-worktree/src/t8_forest/t8_forest_cxx.cxx:62
> 62	      maxlevel = ts->t8_element_maxlevel ();
> (gdb) where
> #0  0x00007ffff7b6dafd in t8_forest_compute_maxlevel (forest=0x5555561a25a0)
>     at ../../source/t8code-second-worktree/src/t8_forest/t8_forest_cxx.cxx:62
> #1  0x00007ffff7b63f87 in t8_forest_commit (forest=0x5555561a25a0)
>     at ../../source/t8code-second-worktree/src/t8_forest/t8_forest.c:545
> #2  0x00007ffff7b6678b in t8_forest_new_uniform (cmesh=0x5555557a3000, scheme=0x5555557a5f40, level=0, 
>     do_face_ghost=0, comm=1140850688) at ../../source/t8code-second-worktree/src/t8_forest/t8_forest.c:1669
> #3  0x0000555555556cdd in build_forest(int, int, int, png2mesh_adapt_context_t const*) ()
> #4  0x00005555555573ea in main ()
> (gdb) 
> ```

I was using a hybrid forest with triangles and quads here, which is probably not yet supported?

Changed it to a quad only (single tree) forest, but still get other errors:

```bash
[t8 1] balance_time: 0.027287
[t8 1] transition_time: 0.000580
Starting search on level 2
[libsc 0] Abort: Assertion '!t8_element_is_subelement (elem)'
[libsc 0] Abort: ../../source/t8code-second-worktree/src/t8_schemes/t8_quads_transition/t8_transition/t8_transition_quad_cxx.cxx:448
[libsc 0] Abort: Obtained 14 stack frames
[libsc 0] Stack 0: libsc-2.8.1.5-0b70-dirty.so(+0xbd84) [0x7f6ff04e0d84]
[libsc 0] Stack 1: libsc-2.8.1.5-0b70-dirty.so(sc_abort+0xa) [0x7f6ff04e018a]
[libsc 0] Stack 2: libsc-2.8.1.5-0b70-dirty.so(sc_abort_verbosev+0) [0x7f6ff04e0740]
[libsc 0] Stack 3: libt8-1.0.0.591-f908f.so(_ZN27t8_subelement_scheme_quad_c22t8_element_ancestor_idEPK10t8_elementi+0x62) [0x7f6ff079f10c]
[libsc 0] Stack 4: libt8-1.0.0.591-f908f.so(+0x6ca12) [0x7f6ff077ba12]
[libsc 0] Stack 5: libsc-2.8.1.5-0b70-dirty.so(sc_array_split+0xa3) [0x7f6ff04e3e23]
[libsc 0] Stack 6: libt8-1.0.0.591-f908f.so(t8_forest_split_array+0xd2) [0x7f6ff077baed]
[libsc 0] Stack 7: libt8-1.0.0.591-f908f.so(+0x6d508) [0x7f6ff077c508]
[libsc 0] Stack 8: libt8-1.0.0.591-f908f.so(+0x6d830) [0x7f6ff077c830]
[libsc 0] Stack 9: libt8-1.0.0.591-f908f.so(t8_forest_search+0x54) [0x7f6ff077c8b2]
[libsc 0] Stack 10: png2mesh_demo(_Z12build_forestiiiPK24png2mesh_adapt_context_t+0x315) [0x56504ea68e41]
[libsc 0] Stack 11: png2mesh_demo(main+0x327) [0x56504ea69426]
[libsc 0] Stack 12: libc.so.6(__libc_start_main+0xe7) [0x7f6fef973c87]
[libsc 0] Stack 13: png2mesh_demo(_start+0x2a) [0x56504ea681aa]
[t8 1] 
[t8 1] print_element called from: t8_forest_adapt
```

**Comment by Flo1314** [comment]
There seems to be a problem since I last merged DLR:main into this feature-branch (https://github.com/DLR-AMR/t8code/pull/294/commits/04b5ac4799e2b0f9bd9bd55631f4db7a939fd37e). At the moment I do not know the exact reason for this problem. On my machine and with the opt build, my code is not crashing but vtks are not build properly anymore - paraview is not able to open them. I need to check all the changes in main that I pulled into this branch last week.

Using the previous commit (https://github.com/DLR-AMR/t8code/pull/294/commits/9c2c10e36dbf12256ffd346477161920c3d7645b) should work. I tested my examples in debug and opt mode, on multiple processes and validated memory management with valgrind. The only (known) issue here at the moment is that subelements are not working properly on forests of multiple trees which has to do with some changes regarding the geometry base class which I pulled into this branch back in summer (here, t8_geometry_base.cxx:44 throws an assertion because of wrong dimensions).

**Comment by Flo1314** [comment]
And yes, hybrid meshes are not supported yet

**Comment by Flo1314** [comment]
I will this close this PR for now. I will fix some issues and make my feature branch compatible with the recent main branch before reopening a new PR.

**Pull request closed without merging**
