### PR TITLE
Feature adapt with balance

### PR DESCRIPTION
**Pull request by holke**
**_Describe your changes here:_**

Implemented the adapt with balance feature.
If a forest should be adapted and balanced, then these operations are now performened in a single step.

To this end, the adapt function will create a marker array of elements to refine, then the balance condition according to this
marker array will be checked and the markes modified, such that the resulting adapted mesh will be balanced.
At the end the adaptation is carried out according to the marker.

New function `t8_forest_set_balance_ext` can explicitely disable this behaviour, such that adapt and balance will be separate steps.

The `t8_test_forest_commit` test should test both variants.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [x] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Comment by holke** [comment]
Note: I coded this 1,5 years ago and did not look over the code again now.
But i believe it should be in a state where we can integrate it.

**Comment by holke** [comment]
Well the tests fail.
But looks like minor problems (warnings).
Will update soon.

**Comment by holke** [comment]
Converted to draft since tests still fail.

**Comment by Davknapp** [comment]
Do not delete this branch, we will continue development!

**Pull request closed without merging**
